### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by dlgarman** [Jaystonian/Cartridges#2]
How to use in simple steps, what I need to do using the st-link/v2 to get up and running.
Please
Dennis

**Comment by Jaystonian** [comment]
Connect SWDIO, SWCLK and GND from the swd header to the V2. Connect 3v3 from the top left 2-pin header to the v2. Connect NRST from v2 to the top-right-most pin of the ethernet header. Connect BOOT0 with a jumper to 5v next to it or to 3v3 to pull it high. 8MHz jumper needs to be in place, not DOTCLK. Jumper the 5v USB header.  Then connect a powered usb cable to the card, and plug the v2 into a usb port. In CubeProgrammer or link utility, you should be able to connect with default settings now.I have confirmed the aluminum-tube style v2 works after updating its st-link firmware. Earlier I couldn't get it to work for some reason and bought a legit v3set, not sure why. I have also confirmed the "blue pill" stm32f103 knockoffs won't connect to the card with these directions.On 31 Oct. 2020 5:06 pm, dlgarman <notifications@github.com> wrote:
How to use in simple steps, what I need to do using the st-link/v2 to get up and running.
Please
Dennis

**Comment by dlgarman** [comment]
Thank you very much
Dennis
